version: "3.7"

services:
  ecrc-frontend:
    container_name: ecrc-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
