version: "3.7"

services:
  ecrc-frontend:
    container_name: ecrc-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ".:/ecrc-frontend"
      - "/node_modules"
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
