version: "3.7"

services:
  ecrc-frontend:
    container_name: ecrc-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/ecrc-frontend"
      - "/node_modules"
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
