version: "3.7"
services:
  #############################################################################################
  ###                               ECRC-API                                                ###
  #############################################################################################
  ecrcapi:
    build:
      context: .
      args:
        - MVN_PROFILES=ecrc-api
        - ECRC_SERVICE_NAME=ecrc-api
    environment:
      - spring_profiles_active=cloud
      - ECRC_BASEURL=${ECRC_BASEURL}
      - ECRC_PASSWORD=${ECRC_PASSWORD}
      - ECRC_USERNAME=${ECRC_USERNAME}
      - ECRC_WHITELIST=${ECRC_WHITELIST}
      - ECRC_SERVER_PORT=${ECRC_SERVER_PORT}
      - ECRC_CORS_MAPPING=${ECRC_CORS_MAPPING}
      - ECRC_CORS_ALLOWED_ORIGINS=${ECRC_CORS_ALLOWED_ORIGINS}
      - ECRC_JWT_HEADER=${ECRC_JWT_HEADER}
      - ECRC_JWT_PREFIX=${ECRC_JWT_PREFIX}
      - ECRC_JWT_SECRET=${ECRC_JWT_SECRET}
      - ECRC_JWT_ROLE=${ECRC_JWT_ROLE}
      - ECRC_OAUTH_IDP=${ECRC_OAUTH_IDP}
      - ECRC_OAUTH_CLIENT_ID=${ECRC_OAUTH_CLIENT_ID}
      - ECRC_OAUTH_SECRET=${ECRC_OAUTH_SECRET}
      - ECRC_OAUTH_SCOPE=${ECRC_OAUTH_SCOPE}
      - ECRC_OAUTH_RETURN_URI=${ECRC_OAUTH_RETURN_URI}
      - ECRC_PAYMENT_URL=${ECRC_PAYMENT_URL}
      - ECRC_PAYMENT_USERNAME=${ECRC_PAYMENT_USERNAME}
      - ECRC_PAYMENT_PASSWORD=${ECRC_PAYMENT_PASSWORD}
      - ECRC_OAUTH_TOKEN_EXPIRY=${ECRC_OAUTH_TOKEN_EXPIRY}
      - ECRC_JWT_AUTH_ROLE=${ECRC_JWT_AUTH_ROLE}
      - ECRC_OAUTH_WELL_KNOWN=${ECRC_OAUTH_WELL_KNOWN}
      - LOG_LEVEL=INFO
      - ECRC_OAUTH_PER_SECRET=${ECRC_OAUTH_PER_SECRET}
    ports:
      - "8086:${ECRC_SERVER_PORT}"
