@ECHO OFF
SETX ECRC_BASEURL http://reeks.bcgov:5555 
SETX ECRC_CORS_ALLOWED_ORIGINS http://localhost:3000/
SETX ECRC_CORS_MAPPING /**
SETX ECRC_OAUTH_CLIENT_ID b7c96106-6bb7-4e8e-9d1a-6820026d3962
SETX ECRC_OAUTH_FE_SECRET ecrc1
SETX ECRC_OAUTH_IDP http://ecrc-oauth-test-server-zbam91-tools.pathfinder.gov.bc.ca/openid-connect-server-webapp
SETX ECRC_OAUTH_RETURN_URI http://localhost:8082/ecrc/auth-callback
SETX ECRC_OAUTH_SCOPE "offline_access openid profile api"
SETX ECRC_OAUTH_SECRET AIlAuvQQdWzuj923Et3-KNcPZ4y4huTDVC33iXt59vahT0EnkvGXcTXx0OVKALlRE2I-JEQwQF5GPLE-PBsiWEY
SETX ECRC_OAUTH_TOKEN_EXPIRY 3000
SETX ECRC_PASSWORD sharkey1
SETX ECRC_SERVER_PORT 8082
SETX ECRC_USERNAME crc_rest
SETX ECRC_WHITELIST crce

PAUSE