name: Build tagged images for ecrc-frontend API and Frontend
on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  frontend-unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/npm-test.yml@feature/npm-test
    with:
      working_directory: src/ecrc-frontend

  api-unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: src/ecrc-api
      java_version: 17

  frontend-build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@main
    needs:
      - frontend-unit-test
    with:
      build_config_name: "ecrc-frontend"
      image_tags: "dev,${{ github.ref_name }}"
    secrets:
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"

  api-build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@main
    needs:
      - api-unit-test
    with:
      build_config_name: "ecrc-api"
      image_tags: "dev,${{ github.ref_name }}"
    secrets:
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"