name: Frontend - Build ecrc-frontend Image for development
on:
  push:
    branches:
      - main
    paths:
      - "src/ecrc-frontend/**"
  workflow_dispatch: {}

jobs:
  unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/npm-test.yml@feature/npm-test
    with:
      working_directory: src/ecrc-frontend

  build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@main
    needs:
      - unit-test
    with:
      build_config_name: "ecrc-frontend"
      image_tags: "dev"
    secrets:
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"